// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates tailored social media posts based on user inputs.
 *
 * - generateSocialMediaPosts - A function that generates social media posts.
 * - GenerateSocialMediaPostsInput - The input type for the generateSocialMediaPosts function.
 * - GenerateSocialMediaPostsOutput - The return type for the generateSocialMediaPosts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSocialMediaPostsInputSchema = z.object({
  productInformation: z
    .string()
    .describe('Detailed information about the product or service.'),
  targetAudience: z.string().describe('The intended audience for the social media posts.'),
  keyMessage: z.string().describe('The core message to be conveyed in the posts.'),
  socialPlatform: z
    .enum([
      'Facebook',
      'Twitter',
      'Instagram',
      'LinkedIn',
      'TikTok',
      'YouTube',
    ])
    .describe('The specific social media platform for the posts.'),
  callToAction: z.string().describe('The desired action from the audience (e.g., Visit our website).'),
  formatConstraints: z
    .string()
    .optional()
    .describe('Any specific formatting requirements for the platform (e.g., character limits).'),
});

export type GenerateSocialMediaPostsInput = z.infer<typeof GenerateSocialMediaPostsInputSchema>;

const GenerateSocialMediaPostsOutputSchema = z.object({
  posts: z
    .array(z.string())
    .describe('An array of social media posts tailored to the specified platform.'),
});

export type GenerateSocialMediaPostsOutput = z.infer<typeof GenerateSocialMediaPostsOutputSchema>;

export async function generateSocialMediaPosts(
  input: GenerateSocialMediaPostsInput
): Promise<GenerateSocialMediaPostsOutput> {
  return generateSocialMediaPostsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSocialMediaPostsPrompt',
  input: {schema: GenerateSocialMediaPostsInputSchema},
  output: {schema: GenerateSocialMediaPostsOutputSchema},
  prompt: `You are a social media marketing expert. Generate social media posts based on the following information for the specified platform, adhering to any format constraints and including a clear call to action.

Product Information: {{{productInformation}}}
Target Audience: {{{targetAudience}}}
Key Message: {{{keyMessage}}}
Social Platform: {{{socialPlatform}}}
Call to Action: {{{callToAction}}}
Format Constraints: {{{formatConstraints}}}

Generate 3 different posts. Return a JSON array of strings.
`, 
});

const generateSocialMediaPostsFlow = ai.defineFlow(
  {
    name: 'generateSocialMediaPostsFlow',
    inputSchema: GenerateSocialMediaPostsInputSchema,
    outputSchema: GenerateSocialMediaPostsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
